name: CI/CD FastAPI with ArgoCD

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/actions.yaml
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/fastapi-app
        IMAGE_TAG=latest-${GITHUB_SHA::7}
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Update Kubernetes manifests
      run: |
        sed -i "s|image: .*$|image: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest-${GITHUB_SHA::7}|" k8s/deployment.yaml

    - name: Commit and Push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest-${GITHUB_SHA::7}"
        git push
