name: CI/CD FastAPI with ArgoCD

on:
  push:
    branches:
      - master
    paths:
      - multimodel_hatespeech_detection/**
      - .github/workflows/build-docker-image.yaml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

#    - name: Build and Push Docker image
#      run: |
#        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/fastapi-app
#        IMAGE_TAG=latest-${GITHUB_SHA::7}
#        docker build -t $IMAGE_NAME:$IMAGE_TAG .
#        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Update Kubernetes manifests in terraform repo
      run: |
        git clone https://github.com/sivanbhfe/multimodel-hate-speech-detection-terraform
        cd multimodel-hate-speech-detection-terraform
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        sed -i "s/newTag:.*/newTag: ${GITHUB_SHA::7}/" apps/multimodal-hatespeech/overlays/prod/kustomization.yaml
        git commit -am "Deploy ml-api ${GITHUB_SHA::7}"
        git push