name: CI/CD FastAPI with ArgoCD

on:
  push:
    branches:
      - master
    paths:
      - multimodel_hatespeech_detection/**
      - .github/workflows/build-docker-image.yaml
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/fastapi-app
        IMAGE_TAG=latest-${GITHUB_SHA::7}
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Update Kubernetes manifests in terraform repo
      run: |
        git clone git@github.com:sivanbhfe/multimodel-hate-speech-detection-terraform.git
        cd multimodel-hate-speech-detection-terraform
        sed -i "s/newTag:.*/newTag: ${GITHUB_SHA::7}/" apps/ml-api/overlays/prod/kustomization.yaml
        git commit -am "Deploy ml-api ${GITHUB_SHA::7}"
        git push